import {
  type AccountsResponse,
  accountsResponseSchema,
  type TransferResponse,
} from "@wallet/shared"
import { walletApi } from "../../app/api.js"
import { parseResponse } from "../../lib/parseResponse.js"

/**
 * FR-3 and FR-10, typed by the same contract the server validates with.
 */
export const accountsApi = walletApi.injectEndpoints({
  endpoints: (build) => ({
    accounts: build.query<AccountsResponse, void>({
      query: () => "/accounts",
      transformResponse: parseResponse(accountsResponseSchema, "accounts"),
      providesTags: ["Accounts"],
    }),

    topUp: build.mutation<TransferResponse, void>({
      query: () => ({
        url: "/accounts/topup",
        method: "POST",
        headers: {
          /*
           * FR-4.4: a fresh v4 uuid per attempt, generated by the client.
           *
           * Generated inside `query` rather than passed in, because the key
           * identifies *this request* and nothing upstream should be able to
           * hand in a used one. `crypto.randomUUID` needs a secure context,
           * which the app has (§20.1 is HTTPS everywhere, and localhost
           * counts).
           */
          "idempotency-key": crypto.randomUUID(),
        },
        // The endpoint refuses an unexpected body, and takes none: the amount
        // is fixed by FR-10.1 and the account comes from the token.
        body: {},
      }),
      /*
       * Both, and this is why the two features share one cache. A top-up
       * changes the balance and writes a row into the history; invalidating
       * only the first leaves a screen showing new money above a list that
       * does not mention it.
       */
      invalidatesTags: ["Accounts", "History"],
    }),
  }),
})

export const { useAccountsQuery, useTopUpMutation } = accountsApi
